added neptun import from authSCH, profile form improvements
kir-dev/schbody pull request #109
Opened 2024-09-26 14:58 UTC by FearsomeRover

2024-09-26 15:03 UTC, mozsarmate requested changes
nice job, ez a ketto kell meg fe-n es szerintem jo lesz

2024-09-26 15:03 UTC, mozsarmate commented on apps/frontend/src/components/ui/ProfileForm.tsx
> +            </FormItem>
ez a fenti kartyan ugyis latszik, innen kikerulhet

2024-09-26 15:03 UTC, mozsarmate commented on apps/frontend/src/zod-form-schemas/ProfileFormSchema.ts
>      isSchResident: z.boolean().optional(),
keruljon ki a neptun mezo a masik formSchemabol is

2024-09-26 15:29 UTC, Tschonti commented
kotelezo volt neptunt megadni eddig a jelentkezeshez, ugye?

2024-09-26 15:31 UTC, FearsomeRover commented
Aha
Viszont ugye arról nem tudjuk fixen, hogy valós. Van valami ötleted, hogyan lehetne most minden eddigi userét updatelni? És akkor utána már nem kell minden loginnál ránézni.

2024-09-26 17:17 UTC, Tschonti commented
szerintem erre nincsen mas mod, minthogy megkerunk mindenkit, hogy jelentkezzen be ujra (esetleg letiltani a fiokjukat, amig nem teszik meg, de ez mar egeszen kocsogseg lenne az igenyles utan)

az OAuth lenyege, hogy csak akkor tudunk adatot lekerni a felhasznalorol, ha o hozzajarul ahhoz, szoval amig nem fogadja el, hogy atadja a neptun kodjat, addig nem tudjuk megszerezni.

mire kell amugy, nem vikes kolisoknak? vagy az egyetemi exporton is ez volt rajta?

2024-09-26 17:18 UTC, Tschonti commented
amugy meg ha valaki szar neptunt adott, akkor az egyetem gondolom visszadobja, es o szivta meg.
az meg hogy van egy update loginnel nem nagy pain, mert a vik statuszt amugy is frissitjuk

2024-09-27 08:37 UTC, FearsomeRover commented
mire kell amugy, nem vikes kolisoknak? vagy az egyetemi exporton is ez volt rajta?
Amúgy ez egész valid. Elsőre ugye az kellett, hogy a neptunban checkelni tudják az aktív félévet. De ugye az azóta már nem manuális. Hát i guess akkor náluk semmire.

2024-09-29 16:21 UTC, Tschonti approved these changes

2024-10-01 22:17 UTC, merged