added posts crud
kir-dev/schbody pull request #14
Opened 2024-07-16 13:14 UTC by FearsomeRover

Closes #2

2024-07-16 16:59 UTC, Isti01 commented on apps/backend/src/posts/posts.service.ts
> +    if (currentPost.authorId !== user.authSchId && user.role !== 'BODY_ADMIN') {
Is it a good idea to only allow the original author to edit/delete posts?

2024-07-16 16:59 UTC, Isti01 commented on apps/backend/src/posts/posts.service.ts
> +    if (currentPost.authorId !== user.authSchId && user.role !== 'BODY_ADMIN') {
Same here

2024-07-23 18:54 UTC, Tschonti commented on apps/backend/src/posts/posts.service.ts
> +  }
prisma update and delete methods throw an exception if no record is found, we should catch so no 500 error is thrown

2024-08-05 14:03 UTC, Tschonti commented on apps/backend/src/posts/posts.controller.ts
> +  }
I think these also need to be annotated with the `@UseGuards(AuthGuard('jwt'))`

2024-08-13 14:37 UTC, Tschonti requested changes
Sorry for reviewing it in stages, I haven't started the app until now 🫠

but these bugs could've easily been found with some basic manual testing xd

2024-08-13 14:37 UTC, Tschonti commented on apps/backend/src/posts/posts.service.ts
> +    }
classic mistake: trying to catch an error in an async call without awaiting it

2024-08-13 14:37 UTC, Tschonti commented on apps/backend/src/posts/posts.service.ts
> +  }
same

2024-08-13 21:44 UTC, Tschonti approved these changes
sorry az előző review elég passzív agresszív volt xd

2024-08-16 21:53 UTC, merged