added basic crud for application periods
kir-dev/schbody pull request #17
Opened 2024-08-13 13:08 UTC by FearsomeRover

Closes #3 
Sry, dunno, why I thought it was #4, so the branch name is wrong.
It seems to be quite painful to fetch all application periods for checking the overlaps. Maybe we can reconsider this.

2024-08-13 14:47 UTC, Tschonti requested changes

2024-08-13 14:47 UTC, Tschonti commented on apps/backend/src/application-period/application-period.service.ts
> +    });
possibly better solution: https://github.com/Tschonti/pontozo/blob/master/packages/functions/src/functions/seasons/create.ts#L21-L30

(elements in the where array are connected with the OR operator)

2024-08-13 14:47 UTC, Tschonti commented on apps/backend/src/application-period/application-period.controller.ts
> +  }
not sure if this was discussed with them, but maybe it'd make sense if only the body admin could do these

2024-08-13 14:47 UTC, Tschonti commented on apps/backend/src/application-period/application-period.controller.ts
> +  }
do regular users need access to the findAll and findOne methods?

2024-08-13 14:47 UTC, Tschonti commented on apps/backend/src/application-period/application-period.service.ts
> +      throw new BadRequestException('Application period not found');
that's usually a NotFoundException

2024-08-13 14:47 UTC, Tschonti commented on apps/backend/src/application-period/application-period.service.ts
> +    }
same thing

2024-08-13 14:47 UTC, Tschonti commented on apps/backend/src/application-period/application-period.service.ts
> +      throw new Error('No current application period found');
this shows up as a 500 error for the user, should be NotFoundException

2024-08-13 21:50 UTC, Tschonti commented on apps/backend/src/application-period/application-period.service.ts
> +    });
wow yours is a much better solution xd

2024-08-13 21:51 UTC, Tschonti approved these changes

2024-08-14 20:32 UTC, Dkrisztan commented
On the create-application dto  I don't see any validation, aren't those needed?

2024-08-20 20:04 UTC, merged